### DISCUSSION TITLE
Need Help. I have no success to write Actual input power in Modbus-register 102

### DISCUSSION THREAD

**Discussion by thoath2** [RalfWinter/lambda-heatpump-modbus-tcp-HA#24] [Q&A]
Hello,
Has any of you ever had success to write the PV excess in the Modbus register 102 of the heat pump?
I have a Lambda heat pump EU13L. I was able to read the Modbus registers very quickly after reading and using this repository. Thank you for that. It was a great help.
My modbus is configured as follows:

```
- name: "wp"
  type: tcp
  host: 192.168.178.xyz
  port: 502
  message_wait_milliseconds: 30
  timeout: 5
  sensors:
 
    # Modul: E-Management (also: Energy-Meter zur Überschussmessung)
    # --------------------------------------------------------------

    - name: wp_emgr_actual_power
      unique_id: wp_emgr_actual_power
      address: 102
      input_type: holding
      unit_of_measurement: "W"
      state_class: total
      scale: 1
      precision: 0
      data_type: uint16 # geändert von int16
      scan_interval: 15
```

I changed the data type from INT16 to Uint16 because I want to use the direct surplus of the inverter (see SPEC)
In addition, I tested the writing of the surplus with automation:

```
- id: pv_ueberschuss_an_wp_senden
  alias: PV-Überschuss an WP senden
  description: Schreibt über Modbus den Wert in die Wärmepumpe
  triggers:
  - minutes: /1
    trigger: time_pattern
  conditions:
  - condition: template
    value_template: '{{ states(''sensor.effektiver_pv_ueberschuss_fuer_wp_v3_lfd_15min_mean_durchschnitt'') not in
      [''unavailable'', ''unknown''] }}'
  - condition: numeric_state
    entity_id: sensor.effektiver_pv_ueberschuss_fuer_wp_v3_lfd_15min_mean_durchschnitt
    above: 0
  actions:
  - data:
      hub: wp
      address: 102
      value: 100
    action: modbus.write_register
  mode: restart
```
I first took a fixed value 100

But I have no success with that. There is an error message in log:

```
Logger: homeassistant.components.modbus.modbus
Quelle: components/modbus/modbus.py:310
Integration: Modbus (Dokumentation, Probleme)
Erstmals aufgetreten: 11:15:01 (21 Vorkommnisse)
Zuletzt protokolliert: 11:35:01

Pymodbus: wp: Error: device: 0 address: 102 -> pymodbus returned isError True
```

Does anyone have an idea what I could do wrong? 
Ciao Thomas

**Comment by RalfWinter** [comment]
Hi Thomas, please have a look [here](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/issues/1) where we discussed how to write the PV surplus to register 102.
Rgds....Ralf

**Reply by thoath2** [reply]
Guten Abend Ralf, 
hab vielen Dank für Deine gestrige Antwort mit dem Link zur passenden Diskussion. Ich habe nicht viel umbauen müssen. Ich kann jetzt tatsächlich das Register 102 beschreiben. Hier meine Automation:
```
- id: pv_ueberschuss_an_wp_senden
  alias: PV-Überschuss an WP senden
  description: Schreibt über Modbus den Wert in die Wärmepumpe
  triggers:
  - minutes: /1
    trigger: time_pattern
  conditions:
  - condition: template
    value_template: '{{ states(''sensor.effektiver_pv_ueberschuss_fuer_wp_v3_lfd_15min_mean_durchschnitt'') not in [''unavailable'',
      ''unknown'', ''none''] }}'
  - condition: numeric_state
    entity_id: sensor.effektiver_pv_ueberschuss_fuer_wp_v3_lfd_15min_mean_durchschnitt
    above: -1
  actions:
  - data:
      address: 102
      hub: wp
      value:
      - '{{states(''sensor.effektiver_pv_ueberschuss_fuer_wp_v3_lfd_15min_mean_durchschnitt'') | int | bitwise_and(65535)}}'
    action: modbus.write_register
  mode: restart
```

Allerdings was ich anders mache. Ich verwende den Konfigurationseintrag "E-Eintrag" beim E-Manager in der Wärmepumpe.

<img width="963" alt="E-Eintrag" src="https://github.com/user-attachments/assets/22658a2d-440f-4f05-860c-842e8c1b69cb" />
<img width="962" alt="E-Eintrag-2" src="https://github.com/user-attachments/assets/d9985bfb-4c06-4294-bda5-dd7924e32fb6" />

Damit "rutscht" das E-Meter in der Betrachtung zwischen PV-Erzeugung und Wärmepumpe. Ich werde es nun in den nächsten Tagen testen, ob es sich bewährt.

Eine Frage, bzw. Beobachtung habe ich noch. Die WP verlangt offensichtlich nach kontinuierlichem Senden des Überschuss-Wertes. Deaktiviere ich die Automation, wird mir nach c.a. 5 Minuten ein Alarm-Fehler "falscher Wert" in der WP angezeigt. Weißt Du, ob man das der WP irgendwie abgewöhnen kann, dass sie im Falle des Ausbleibens zum Beispiel auf einen Default-Wert zurückfällt?
Einen schönen Abend
Thomas
