### ISSUE TITLE
PV Überschuss vom Smartmeter überschreiben

### ISSUE THREAD

**Issue by onestyle1** [RalfWinter/lambda-heatpump-modbus-tcp-HA#31]
Hallo allerseits

Ich möchte gerne erzielen, dass die Lambda nur dann den PV Überschuss nutzt, wenn auch ca. die Tageshöchsttemperatur erreicht ist. Mein erster Ansatz war, eine Automation, welche Register 102 am Vormittag regelmässig mit Null überschreibt. Leider scheint das (noch) nicht zu funktionieren:
```
alias: Lambda Automation Überschuss nur am Nachmittag
description: ""
triggers:
  - minutes: /1
    trigger: time_pattern
conditions:
  - condition: time
    after: "06:00:00"
    before: "13:15:00"
actions:
  - data:
      hub: EU08L
      unit: 1
      address: 102
      value: 0
    action: modbus.write_register
mode: single
```
Könnte mir jemand auf die Sprünge helfen? Oder ist das so nicht möglich? Gibt es einen anderen Ansatz? Grundsätzlich möchte ich so wenig eingreifen wie möglich, also den Lambda-Smartmeter ganz ausschalten und die Werte vom Fronius Smartmeter nur am Nachmittag manuell einspeisen wäre nicht meine favorisierte Lösung.
